### PR TITLE
Changed emoji polyfill to only occur on platforms that don't have emoji

### PR DESCRIPTION
**Pull request by peabnuts123**
Added a Modernizr build configuration to the project and re-added an old definition to test for Emoji support. Changed logic of emoji polyfill to check for Emoji support. Tested and working on iOS Chrome and Safari + Debian Chrome

### CODE REVIEW

**Comment by peabnuts123** [comment]
GG breaking build, hold up

**Comment by peabnuts123** [comment]
Stayed up 2 hours past my bed time to support fucking emojis on this shitty site. I HOPE YOU'RE HAPPY

**Comment by peabnuts123** [comment]
Oops i referenced the wrong issue.

**Comment by ryankurte** [comment]
Love your work ^_^
Checked out and working on my system, so, lets do it live!

**Pull request merged**
